Add FIFO features and relative examples
stm32duino/LSM6DSV16X pull request #5
Opened 2023-02-09 13:30 UTC by davideq

2023-02-09 14:33 UTC, fpistm requested changes

2023-02-09 14:33 UTC, fpistm commented on src/LSM6DSV16XSensor.cpp
> +<<<<<<< HEAD
Seems there are merge issue.

2023-02-09 16:01 UTC, fpistm requested changes
Some simplification could be done.
One local variable useless.
Probably some hardening could be done linked to returned error code.
else LGTM

2023-02-09 16:01 UTC, fpistm commented on examples/LSM6DSV16X_FIFO_Interrupt/LSM6DSV16X_FIFO_Interrupt.ino
> +  AccGyr.FIFO_Get_Num_Samples(&samples_to_read);
What happens if function failed? Seems `FIFO_Get_Num_Samples `return a status.
As it is not checked, I guess `samples_to_read `is set to 0 by default so no read performed in the below for loop.

2023-02-09 16:01 UTC, fpistm commented on examples/LSM6DSV16X_FIFO_Interrupt/LSM6DSV16X_FIFO_Interrupt.ino
> +    AccGyr.FIFO_Get_Full_Status(&fullStatus);
Same here about `fullStatus `no check if `FIFO_Get_Full_Status` is successful.

2023-02-09 16:01 UTC, fpistm commented on examples/LSM6DSV16X_FIFO_Interrupt/LSM6DSV16X_FIFO_Interrupt.ino
> +
Same here, seems some of above methods return a status but it is assume all goes ok.

Maybe something like this could be added:

LSM6DSV16XStatusTypeDef status = LSM6DSV16X_OK;
status |= AccGyr.FIFO_Set_Watermark_Level(FIFO_SAMPLE_THRESHOLD);
....
if (status != LSM6DSV16X_OK) {
  Serial.prinln("LSM6DSV16X Sensor failed to init/configure");
  while(1);
}

2023-02-09 16:01 UTC, fpistm commented on examples/LSM6DSV16X_Double_Tap_Detection/LSM6DSV16X_Double_Tap_Detection.ino
> +#define INT1_pin PA4
Maybe add a comment to warn user he have to update it if he uses an other pin? Same in other examples.

2023-02-09 16:01 UTC, fpistm commented on examples/LSM6DSV16X_FIFO_Polling/LSM6DSV16X_FIFO_Polling.ino
> +
Same here assuming all is ok

2023-02-09 16:01 UTC, fpistm commented on src/LSM6DSV16XSensor.cpp
> +  return LSM6DSV16X_OK;
```suggestion
  return lsm6dsv16x_read_reg(&reg_ctx, LSM6DSV16X_FIFO_DATA_OUT_X_L, Data, 6);
```

2023-02-09 16:01 UTC, fpistm commented on src/LSM6DSV16XSensor.cpp
> +
```suggestion
  return lsm6dsv16x_fifo_data_level_get(&reg_ctx, NumSamples);
```

2023-02-09 16:01 UTC, fpistm commented on src/LSM6DSV16XSensor.cpp
> +  return LSM6DSV16X_OK;
```suggestion
  return lsm6dsv16x_fifo_watermark_set(&reg_ctx, Watermark);
```

2023-02-09 16:01 UTC, fpistm commented on src/LSM6DSV16XSensor.cpp
> +  return LSM6DSV16X_OK;
```suggestion
  return lsm6dsv16x_fifo_stop_on_wtm_set(&reg_ctx, Status) != LSM6DSV16X_OK);
```

2023-02-09 16:01 UTC, fpistm commented on src/LSM6DSV16XSensor.cpp
> +  return LSM6DSV16X_OK;
```suggestion
  return lsm6dsv16x_fifo_xl_batch_set(&reg_ctx, new_bdr);
```

2023-02-09 16:01 UTC, fpistm commented on src/LSM6DSV16XSensor.cpp
> +  return LSM6DSV16X_OK;
```suggestion
  return lsm6dsv16x_fifo_gy_batch_set(&reg_ctx, new_bdr);
```

2023-02-20 12:56 UTC, davideq commented
> edits done and committed.

2023-02-20 13:07 UTC, fpistm approved these changes
LGTM

2023-03-01 08:08 UTC, merged